author: Chris Zuber
title: Chris Zuber
version: 3.2.15
description: "A responsive, progressive about / portfolio & blog page built using Jekyll"
keywords:
  - jekyll
  - Chris Zuber
  - Web Developer
  - portfolio
  - CSS3
  - HTML5
  - responsive design
  - progressive web app
  - pwa
  - ecmascript
  - javascript
  - es6
markdown: kramdown
respository: "shgysk8zer0/shgysk8zer0.github.io"
lang: en_US
dir: ltr
feed: /feed.rss
icons: '/img/icons.svg'
theme-color: '#FC5B0B'
github:
  username: shgysk8zer0
  repo: shgysk8zer0.github.io
  url: "https://shgysk8zer0.github.io"
twitter: SudoDevTeam
gravatar: 73f08dc9b030c584e76a4c3c4e8a56c0
webmaster-verifications:
  google: 0cMX_-aKH-pe1wQXGDlK833KE3-kN5V7y3eaywoCXdk
  bing: D0C151304642EDCA64F73FE5C4B43D7A
robots: 'follow,index'
appicons:
  - src: /img/favicon.svg
    sizes: any
    type: image/svg+xml
  - src: /img/icon-512.png
    sizes: 512x512
    type: image/png
  - src: /img/icon-192.png
    sizes: 192x192
    type: image/png
screenshots:
  - src: 'https://i.imgur.com/Ers0Xql.png'
    sizes: 649x604
    type: image/png
paginate: 5
paginate_path: "/posts/page-:num/"
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Chris Zuber"
      permalink: /posts/:categories/:year/:month/:day/:title/
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
      author: "Chris Zuber"
      permalink: /posts/:categories/:year/:month/:day/:title/
plugins:
  - jekyll-gist
  - jekyll-youtube
  - jekyll-admin
  - jekyll-avatar
  # - jekyll-mentions
  # - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-include-cache
  # - jekyll-seo-tag
  # - jemoji
  # - jekyll-octicons
exclude:
- "*.rb"
- "*.gemspec"
- "*.php"
- "*.sh"
- "*.csv"
- "*.sfd"
- "*.ai"
- "*.psd"
- "*.sketch"
- "*.yml"
- "*.lock"
- "*.log"
- "/css/*.md"
- "/js/*.md"
- "/img/*.md"
- "/fonts/*.md"
- "/js/*.json"
- "/css/*.json"
- "/img/*.json"
- "/js/*.html"
- Gemfile
- node_modules/
- docs
- palette.xml
- postcss.config.js
- postcss.config.json
- README.md
- LICENSE
- "*.config.js"
- "/img/octicons/test"
- "/img/octicons/*.js"
- "/img/octicons/*.md"
- "/img/octicons/LICENSE"
- "/img/octicons/lib/*.css"
- "/img/octicons/lib/octicons_gem"
- "/img/octicons/lib/octicons_node"
- "/img/octicons/lib/octicons_helper"
- "/img/octicons/lib/jekyll-octicons"
- "/img/octicons/script"
- "/img/adwaita-icons/docs"
- "/img/adwaita-icons/LICENSE"
- "css/core-css/docs"
- "css/normalize/*.html"
- "js/std-js/docs"
- "js/std-js/test"
