author: Chris Zuber
title: Chris Zuber
description: "A responsive, progressive about / portfolio & blog page built using Jekyll"
env: production
markdown: kramdown
plugins:
  - jekyll-gist
  - jekyll-youtube
keep_files:
- ".well-known/"
- ".well-known/*"
exclude:
- Gemfile
- Gemfile.lock
- "*.log"
- node_modules/
- docs
- palette.xml
- me.json
- package.json
- postcss.config.js
- postcss.config.json
- README.md
- LICENSE
- rollup.config.js
- "img/octicons/test"
- "img/octicons/*.js"
- "img/octicons/LICENSE"
- "img/octicons/*.json"
- "img/octicons/*.md"
- "img/octicons/lib/*.json"
- "img/octicons/lib/*.sketch"
- "img/octicons/lib/*.css"
- "img/adwaita-icons/*.php"
- "img/adwaita-icons/*.md"
- "img/adwaita-icons/docs"
- "img/adwaita-icons/LICENSE"
- "css/core-css/docs"
- "css/normalize/*.md"
- "css/normalize/*.json"
- "css/normalize/*.html"
- "js/std-js/docs"
- "js/std-js/test"
