author: Chris Zuber
title: Chris Zuber
description: "A responsive, progressive about / portfolio & blog page built using Jekyll"
markdown: kramdown
respository: "shgysk8zer0/shgysk8zer0.github.io"
github:
  url: "https://shgysk8zer0.github.io"
twitter:
  username: shgysk8zer0
webmaster_verifications:
  google: "0cMX_-aKH-pe1wQXGDlK833KE3-kN5V7y3eaywoCXdk"
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Chris Zuber"
      permalink: /posts/:categories/:year/:month/:day/:title/

  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
      author: "Chris Zuber"
      permalink: /posts/:categories/:year/:month/:day/:title/
plugins:
  - jekyll-gist
  - jekyll-youtube
  - jekyll-admin
  - jekyll-avatar
  # - jekyll-mentions
  # - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-include-cache
  # - jekyll-seo-tag
  # - jemoji
  # - jekyll-octicons
exclude:
- "*.rb"
- "*.php"
- "*.sh"
- "*.csv"
- "*.json"
- "*.sfd"
- "*.ai"
- "*.psd"
- "*.sketch"
- "*.yml"
- "*.lock"
- "*.log"
- Gemfile
- node_modules/
- docs
- palette.xml
- postcss.config.js
- postcss.config.json
- README.md
- LICENSE
- "*.config.js"
- "img/octicons/test"
- "img/octicons/*.js"
- "img/octicons/*.md"
- "img/octicons/LICENSE"
- "img/octicons/lib/*.css"
- "img/adwaita-icons/docs"
- "img/adwaita-icons/LICENSE"
- "css/core-css/docs"
- "css/normalize/*.html"
- "js/std-js/docs"
- "js/std-js/test"

