author: Chris Zuber
title: Portfolio
description: Contact info and work examples for Chris Zuber
keywords: Chris Zuber, portfolio
theme_color: "#FC5B0B"
publisher_url: https://plus.google.com/+Chriszuber_dot_com
author_url: https://plus.google.com/+ChrisZuber
url: https://shgysk8zer0.github.io
scripts:
- src: "/js/index.min.js"
  type: application/javascript
  async: true
  defer: false
  nomodule: false
- src: "https://cdn.polyfill.io/v2/polyfill.min.js"
  type: application/javascript
  async: false
  defer: false
  nomodule: false
stylesheets:
- href: "/css/styles/index.min.css"
  media: all
markdown: kramdown
exclude:
- node_modules/
- docs
- palette.xml
- me.json
- package.json
- postcss.config.js
- postcss.config.json
- README.md
- LICENSE
- rollup.config.js
- "img/octicons/test"
- "img/octicons/*.js"
- "img/octicons/LICENSE"
- "img/octicons/*.json"
- "img/octicons/*.md"
- "img/octicons/lib/*.json"
- "img/octicons/lib/*.sketch"
- "img/octicons/lib/*.css"
- "img/adwaita-icons/*.php"
- "img/adwaita-icons/*.md"
- "img/adwaita-icons/docs"
- "img/adwaita-icons/LICENSE"
- "css/core-css/docs"
- "css/normalize/*.md"
- "css/normalize/*.json"
- "css/normalize/*.html"
- "js/std-js/docs"
- "js/std-js/test"
